### PR TITLE
Fix Iceberg snapshot issue of incorrect DROP VIEW calls

### LINKED ISSUE #543: DROP VIEW is called for Iceberg table created by dbt snapshot
### Describe the bug

dbt snapshot fails with error `database.table__dbt_tmp is a table. 'DROP VIEW' expects a view. Please use DROP TABLE instead.`

### Expected behavior
DROP TABLE is called for Iceberg table instead of DROP VIEW.

### PR DESCRIPTION
**Pull request by moomindani**
resolves #543

### Description

This PR is to fix Iceberg snapshot issue of incorrect DROP VIEW calls.

### Checklist

- [x] I have run this code in development and it appears to resolve the stated issue
- [] This PR includes tests, or tests are not required/relevant for this PR
- [x] I have updated the `CHANGELOG.md` and added information about my change to the "dbt-glue next" section.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by aajisaka** [comment]
Do you have any regression test for this issue?

File: dbt/include/glue/macros/materializations/snapshot.sql [hunk 1]
```diff
@@ -74,13 +74,22 @@
...
-        {% for column in columns %}
-          `{{ column.name }}` {{ column.data_type }} {{- ',' if not loop.last -}}
-        {% endfor %}
-      );
-    {% endcall %}
+      {% set filtered_columns = [] %}
+      {% for column in columns %}
+        {% if not column.name.startswith('dbt_') %}
+          {% do filtered_columns.append(column) %}
+        {% endif %}
```
Comment (aajisaka) [inline dbt/include/glue/macros/materializations/snapshot.sql:81]: Would you document why it needs to filter out the columns starting from `dbt_`?

Comment (moomindani) [reply dbt/include/glue/macros/materializations/snapshot.sql:81]: I tried to implement both unit test and integration test, however I could not make it because ...
* (unit test) test_macros.py: The target macro has internal macro statement which depends on Jinja2 template, which is difficult and tricky to mock in the unit test.
* (integ test) test_iceberg.py: I tried to add one more test case triggering "dbt snapshot" three times, and it definitely caused similar error in dbt.log but it was still very difficult to assert that specific condition inside the test case.

For now, I have reproduced the exact same issue in dbt project, and verified that the pull request successfully resolved the error.

Comment (aajisaka) [reply dbt/include/glue/macros/materializations/snapshot.sql:81]: Thanks. I got it, approving.

**Comment by moomindani** [comment]
> Do you have any regression test for this issue?

I tried to implement both unit test and integration test, however I could not make it because ...
* (unit test) test_macros.py: The target macro has internal macro statement which depends on Jinja2 template, which is difficult and tricky to mock in the unit test.
* (integ test) test_iceberg.py: I tried to add one more test case triggering "dbt snapshot" three times, and it definitely caused similar error in dbt.log but it was still very difficult to assert that specific condition inside the test case.

For now, I have reproduced the exact same issue in dbt project, and verified that the pull request successfully resolved the error.

File: dbt/include/glue/macros/materializations/snapshot.sql (hunk 1 above)
Comment (moomindani) [reply dbt/include/glue/macros/materializations/snapshot.sql:81]: In the current implementation, when we do not filter out columns starting with `dbt_`, new meta columns called `dbt_unique_key_1`, `dbt_unique_key_2`, ...., `dbt_unique_key_N` are accidentally added to the table definition permanently, and this cause further issues in subsequent dbt snapshot runs.

Comment (aajisaka) [reply dbt/include/glue/macros/materializations/snapshot.sql:81]: Thanks. Is it possible to write the above explanation as a comment in the source code?

**Review by aajisaka — APPROVED** [review]
